src/Mocking.jl

Since static compilation doesn't run the `__init__` function none of the globals were being initialized resulting in a UndefVarError. The globals do not need to be in the `__init__` and are safe to reside at the top level.

Fix static compilation for packages using Mocking

---

README.md
src/Mocking.jl
test/runtests.jl

Removes the functionality which automatically called `Mocking.enable()` in Julia 0.5+. This functionality was being triggered unintentionally too often which could lead to confusion.
Fixes #7

Remove implicit enabling of Mocking

---

src/Mocking.jl
test/closure.jl
test/concept.jl

The Julia PR https://github.com/JuliaLang/julia/pull/17057 (the fix for issue https://github.com/JuliaLang/julia/issues/265) introduced some changes which made it invalid to call a function which was compiled after the function containing the call was compiled. This particular problem would occur when using the `apply` do-block patching.

Fixes for automatic recompilation of dependent functions

---

src/Mocking.jl

On Julia 0.6 the old pair expression was producing errors:
```
LoadError: syntax: invalid syntax (=> (inert Integer) (outerref Integer))
```
The new expression appears compatible with Julia 0.4 onwards.

Update pair generation expression

---

REQUIRE
src/Mocking.jl

Updates the code to make use of the `invokelatest`added in https://github.com/JuliaLang/julia/pull/19784

Switch to using invokelatest

---

src/Mocking.jl
src/bindings.jl
src/expr.jl
test/anonymous-param.jl
test/bindings/bindings.jl
test/bindings/ingest_assertion.jl
test/bindings/ingest_default.jl
test/bindings/ingest_parameter.jl
test/bindings/ingest_parametric.jl
test/bindings/ingest_signature.jl
test/bindings/ingest_signature_0.6.jl
test/expr.jl
test/patch.jl
test/runtests.jl

Updated the binding extraction code to be much more accurate and work with the new Julia 0.6 syntax. These changes have allowed the absolute signature code to be drastically simplified. I've maintained support with Julia 0.4 for now but I'll probably drop Julia 0.4 and 0.5 support once this is merged and tagged.
Fixes #15

Overhaul binding extraction

---

.travis.yml
README.md
appveyor.yml
src/Mocking.jl
src/deprecated.jl
src/options.jl
test/runtests.jl

When `--compile-modules=yes` (formerly `--compilecache=yes`) is enabled during a `Pkg.test` it is quite likely that the `@mock` will not work as they have been pre-compiled as no-ops. Currently  if `Pkg.test` is run with compile modules enabled Mocking will report a warning and the tests that require Mocking can be skipped.
Unfortunately, for packages that rely heavily on mocked tests skipping most of the test suite isn't a great solution and some tools, like the JuliaCIBot, provide the user has no control of the options Julia is run with.
This PR provides a mechanism to set `--compile-modules=no` from within Julia itself by modifying the JLOptions C global.

Programmatically disable compile-modules

---

src/Mocking.jl
src/deprecated.jl
src/options.jl
test/compiled-modules.jl
test/precompile.jl
test/runtests.jl

As part of #12 it was decided to move away from using "precompile" to talk about pre-compiled modules and instead use the Julia 0.7 term of "compiled modules". When updating the code I failed to update the functions using the precompile term and used "compile modules" instead of "compiled modules".

Finish renaming pre-compile

---

REQUIRE
src/options.jl

Fixing the deprecation for `nfields` works around this Base issue: https://github.com/JuliaLang/julia/issues/24658

Fix latest Julia 0.7

---

test/patch.jl

Issue was introduced by a new `cos` method added in https://github.com/JuliaLang/julia/pull/24653.

Fix test failure on Julia 0.7

---

src/Mocking.jl
src/expr.jl

- Changes to `import` syntax (https://github.com/JuliaLang/julia/pull/25256)
- Changes to `do` block syntax (https://github.com/JuliaLang/julia/pull/23718)

Address some Julia 0.7 syntax changes

---

src/Mocking.jl
src/expr.jl
test/optional.jl

Handles `@mock` calls with keyword arguments (both `:parameters` and regular `:kw`). Currently, left the `QuoteNode` on kwarg values out as it won't be necessary with #20.
Fixes: #19

Added support for kwargs in `@mock` calls.

---

src/deprecated.jl

I forgot to do this when I did the 0.5 release.

Remove Mocking 0.4 deprecations

---

src/Mocking.jl
test/runtests.jl

By explicitly pulling only the features used from Compat it is easier to determine what version of Compat is actually required by the package and makes it easier to determine when the Compat package is not longer being used.

Explicitly import Compat features

---

README.md
src/Mocking.jl
test/patch.jl

Currently, using nested modules can result in an `UndefVarError`.
```
julia> using Mocking
julia> Mocking.enable(; force=true)
Warning: Using experimental code which modifies jl_options global struct
julia> module A
module B
abstract type AbstractFoo end
struct Foo <: AbstractFoo
x::String
end
end
bar(f::B.AbstractFoo) = println("blah")
end
A
julia> import A: bar
julia> patch = @patch bar(f::B.AbstractFoo) = println("blar")
Mocking.Patch(:(bar(f::A.B.AbstractFoo)), ##665, Set(Any[:(A.B)]))
julia> Mocking.apply(patch) do
bar(B.Foo("Blar"))
end
ERROR: UndefVarError: A not defined
Stacktrace:
[1] Mocking.PatchEnv(::Mocking.Patch, ::Bool) at /Users/rory/.playground/share/mocking/packages/v0.6/Mocking/src/Mocking.jl:156
[2] apply(::Function, ::Mocking.Patch) at …
```

Handle nested modules

---

src/dispatch.jl
src/mock.jl
test/import.jl

I messed the logic up when implementing `get_alternate`. The original method output should be provided when a patch is present for the target function but we do not use the alternate version due to the alternate signature not matching the arguments provided.

Fix debugging messages

---

src/expr.jl
test/mock.jl
test/optional.jl
test/runtests.jl

Fixes https://github.com/invenia/Mocking.jl/issues/85

Support required keywords in `@mock`

---

Project.toml
src/Mocking.jl
src/patch.jl
test/merge.jl
test/nested_apply.jl
test/runtests.jl

Support nested calls to apply, by applying all patches in the current environment, as well as those passed to apply.

Add support for nested calls to apply

---

Project.toml

This PR adds support for Compat >= 4. In 4.0.0 many dependencies were removed by dropping support for Julia < 1.6.
It seems CompatHelper does not create PRs for Compat@4 currently (same happened in e.g. CRC). I wonder if the problem is that CompatHelper pulls in Compat@3, possibly due to its dependency on Mocking. So possibly updating Mocking will resolve the issue.

Support Compat@4

---

Project.toml

The current version in the Julia registry is still 0.7.3 since 0.7.4 was yanked due to [problems with ContextVariablesX.jl](https://github.com/invenia/Mocking.jl/pull/93). Some commits later [a new version was tried to be registered](https://github.com/invenia/Mocking.jl/commit/1eb1e7fb3783c0a78900d6880bcac368905a464f) which did fail due to reuse of the yanked version number. This PR increments the version number such that a new version can be registered.

Change version number to 0.7.5

---

Project.toml
src/Mocking.jl
test/activate.jl
test/runtests.jl

- to allow enabling mocking for a limited scope, rather than users having to write their own `try ... finally` blocks to turn off mocking

Add `activate` method taking function

---

src/mock.jl
test/async-world-ages.jl
test/runtests.jl

Allow patching a mocked call that is running in an older world age by changing the macro to invoke the patch through `invokelatest`.
The call was already inherently going to be a dynamic dispatch anyway, since by definition the whole point is that we want to substitute in a new function later. Invokelatest will just allow us to substitute in a function that was even _defined_ later, after this function had started running.
This doesn't add any extra overhead, nor introduce any restrictions. The only thing that it does is increase the scenarios that Mocking supports.
Fixes #108.
CC: @msagarpatel, @charnik

[#108] Support mocks running a background task

---

src/mock.jl
src/patch.jl

Previously, the macro required `Mocking` to be visible in the caller's context: It was invoking `Mocking.activated()`, for exmaple.  Now it invokes `$activated()`, which makes sure that the code uses the right version of `activated`.  Similarly for `get_alternate` and `Patch`.
Also, the macro was doing some unceessary `gensym` calls, which macro hygene can take care of automatically.

Fix up the scoping for the `@mock` macro.

---

.github/workflows/CI.yml
.github/workflows/CompatHelper.yml
.github/workflows/JuliaNightly.yml
.github/workflows/blue_style_formatter.yml

These workflows haven't been updated in some time. One of the big changes here is now just running on Linux x86-64. There isn't any OS/architecture specific code here so this should speed up CI.

Modernize CI workflows

---

test/patch.jl

Fixes these warnings when running the tests on Julia 1.7 and above:
```
┌ Warning: macroexpand no longer throws a LoadError so `@test_throws LoadError ...` is deprecated and passed without checking the error type!
│   caller = macro expansion at patch.jl:3 [inlined]
└ @ Core ~/.julia/dev/Mocking/test/patch.jl:3
┌ Warning: macroexpand no longer throws a LoadError so `@test_throws LoadError ...` is deprecated and passed without checking the error type!
│   caller = macro expansion at patch.jl:7 [inlined]
└ @ Core ~/.julia/dev/Mocking/test/patch.jl:7
┌ Warning: macroexpand no longer throws a LoadError so `@test_throws LoadError ...` is deprecated and passed without checking the error type!
│   caller = macro expansion at patch.jl:11 [inlined]
└ @ Core ~/.julia/dev/Mocking/test/patch.jl:11 …
```

Fix tests using `macroexpand`

---

src/Mocking.jl
test/activate.jl

Found some minor changes I wanted to make to `activate` before I ended up deprecating the function. 
Something non-obvious is that calling `deactivate` from `activate(f)` now requires `Base.invokelatest` in order for the tests to work. I updated `activate()` to do the same for consistent behaviour.

Minor refactor to activate

---

src/Mocking.jl
src/deprecated.jl
test/activate.jl

As of Julia 1.10 we receive warnings like the following when running `Mocking.activate()`:
```
WARNING: Method definition activated() in module Mocking at /Users/cvogt/.julia/dev/Mocking/src/Mocking.jl:15 overwritten at /Users/cvogt/.julia/dev/Mocking/src/Mocking.jl:24.
```
As the method efinition overwrite is intentional here as we purposefully make use of invalidation to support `@mock` it would be best to silence this warning for end users.
We can use the Julia flag `--warn-overwrite=no` to do this (which is the default) but running `Pkg.test()` seems to enable this flag.
In order to silence this error message we're now avoiding overwriting an existing method and now we are instead just defining a more specific method which ends up having the same result but without the warning. We can …

Avoid overwrite warning using more specific method

---

.JuliaFormatter.toml
.github/workflows/Format.yml
src/dispatch.jl
src/expr.jl
test/anonymous-param.jl
test/dispatch.jl
test/functions.jl
test/mock-in-patch.jl
test/real-nested.jl
test/reuse.jl
test/targets.jl

Adds a `.JuliaFormatter.toml` so that the package formatting style can be applied locally. I've also applied the formatting to the entire repo.

Specify code style with a configuration file

---

.github/workflows/CI.yml
.github/workflows/Documenter.yml
.gitignore
Project.toml
README.md
docs/Project.toml
docs/make.jl
docs/src/api.md
docs/src/faq.md
docs/src/index.md
src/dispatch.jl
src/mock.jl
src/patch.jl
test/randdev.jl
test/runtests.jl

Added Documenter documentation to the package.

Package documentation

---

.github/workflows/TagBot.yml

Trying TagBot without setting an SSH key. Ideally will fix this issue: https://github.com/JuliaTesting/Mocking.jl/actions/runs/10060882479/job/27809542799

Drop SSH key from TagBot

---

docs/src/faq.md

I've added an FAQ entry on how to call the "un-patched" version of a function inside a patch (if you e.g. want to modify the arguments before calling a function).
@omus mentioned that using `@mock` inside a patch can be useful as well but I couldn't immediately come up with an example off the top of my head, so I just left a short note about that being possible.

FAQ entry on calling un-patched function inside patch
